### ISSUE TITLE
Multi-terminal HVDC features tracking 

### ISSUE THREAD

**Issue by jd-lara** [NREL-Sienna/PowerSimulations.jl#1113]
- [x] Include Multi-terminal HVDC in interfaces 
- [x] Include Multi-terminal HVDC in interarea exchanges 
- [ ] Add Loses to Multi-terminal HVDC
- [ ] #1444
